In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import os
from os import walk
import fastf1

In [1]:
import fastf1.plotting

In [3]:
pip install fastf1

Collecting fastf1
  Downloading fastf1-2.3.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.4/79.4 kB 936.0 kB/s eta 0:00:00 0:00:01m
Collecting signalr-client-aio
  Downloading signalr_client_aio-0.0.1.6.2-py2.py3-none-any.whl (8.0 kB)
Collecting thefuzz
  Downloading thefuzz-0.19.0-py2.py3-none-any.whl (17 kB)
Collecting timple>=0.1.2
  Downloading timple-0.1.5-py3-none-any.whl (17 kB)
Requirement already satisfied: numpy>=1.17.3 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from fastf1) (1.21.5)
Requirement already satisfied: requests in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from fastf1) (2.28.1)
Collecting requests-cache>=0.8.0
  Downloading requests_cache-0.9.8-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.7/48.7 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: scipy in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from fastf1) (1.7.3)
Requirement already satisfied: pandas>=1.1.0 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from fastf1) (1.4.4)
Requirement already satisfied: matplotlib>=3.3.3 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from fastf1) (3.6.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (9.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (1.0.5)
Requirement already satisfied: packaging>=20.0 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (21.3)
Requirement already satisfied: cycler>=0.10 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.3->fastf1) (4.25.0)
Requirement already satisfied: pytz>=2020.1 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.1.0->fastf1) (2022.1)
Collecting cattrs>=22.2
  Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)
Requirement already satisfied: urllib3>=1.25.5 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from requests-cache>=0.8.0->fastf1) (1.26.13)
Collecting url-normalize>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: attrs>=21.2 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from requests-cache>=0.8.0->fastf1) (22.1.0)
Requirement already satisfied: appdirs>=1.4.4 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from requests-cache>=0.8.0->fastf1) (1.4.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from requests->fastf1) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from requests->fastf1) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from requests->fastf1) (2022.12.7)
Collecting websockets>=4.0.1
  Downloading websockets-10.4-cp39-cp39-macosx_10_9_x86_64.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 3.6 MB/s eta 0:00:00
Collecting exceptiongroup
  Downloading exceptiongroup-1.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /Users/deepthivarun/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.3->fastf1) (1.16.0)
Installing collected packages: thefuzz, websockets, url-normalize, exceptiongroup, signalr-client-aio, cattrs, timple, requests-cache, fastf1
Successfully installed cattrs-22.2.0 exceptiongroup-1.1.0 fastf1-2.3.0 requests-cache-0.9.8 signalr-client-aio-0.0.1.6.2 thefuzz-0.19.0 timple-0.1.5 url-normalize-1.4.3 websockets-10.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
folder = 'F1_Data'
fastf1.Cache.enable_cache('cache')

In [14]:
driver_standings_df = pd.read_csv("../Analysis/F1_Data/driver_standings.csv")
drivers_df = pd.read_csv("../Analysis/F1_Data/drivers.csv")
result_df = pd.read_csv("../Analysis/F1_Data/results.csv")
race_df = pd.read_csv("../Analysis/F1_Data/races.csv")

In [26]:
rd=pd.merge(result_df,drivers_df,on='driverId')
rdr=pd.merge(rd,race_df,on='raceId')
driver_race_df=rdr
driver_race_df

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,18,1,1,22,1,1,1,1,10.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,18,2,2,3,5,2,2,2,8.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,18,3,3,7,7,3,3,3,6.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,18,4,4,5,11,4,4,4,5.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,18,5,1,23,3,5,5,5,4.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,20119,837,786,51,12,3,2,2,2,6.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
25836,20128,837,774,154,20,13,\N,R,11,0.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
25837,20127,837,780,105,30,11,10,10,10,0.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
25838,20126,837,785,126,26,12,9,9,9,0.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
25839,20129,837,793,154,6,5,\N,R,12,0.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [30]:
# Create Driver column name  
driver_race_df["Driver"] = driver_race_df["forename"] + " " + driver_race_df["surname"]
driver_race_df.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,driver,Driver
0,1,18,1,1,22,1,1,1,1,10.0,...,\N,\N,\N,\N,\N,\N,\N,\N,Lewis Hamilton,Lewis Hamilton
1,2,18,2,2,3,5,2,2,2,8.0,...,\N,\N,\N,\N,\N,\N,\N,\N,Nick Heidfeld,Nick Heidfeld
2,3,18,3,3,7,7,3,3,3,6.0,...,\N,\N,\N,\N,\N,\N,\N,\N,Nico Rosberg,Nico Rosberg
3,4,18,4,4,5,11,4,4,4,5.0,...,\N,\N,\N,\N,\N,\N,\N,\N,Fernando Alonso,Fernando Alonso
4,5,18,5,1,23,3,5,5,5,4.0,...,\N,\N,\N,\N,\N,\N,\N,\N,Heikki Kovalainen,Heikki Kovalainen

In [37]:
#move Driver name to first col
cols = driver_race_df.columns.tolist()
cols.insert(0, cols.pop(cols.index('Driver')))
driver_race_df = driver_race_df.loc[:, cols].drop('driver', axis=1)
driver_race_df.head()

,Driver,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,...,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,Lewis Hamilton,1,18,1,1,22,1,1,1,1,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,Nick Heidfeld,2,18,2,2,3,5,2,2,2,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,Nico Rosberg,3,18,3,3,7,7,3,3,3,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,Fernando Alonso,4,18,4,4,5,11,4,4,4,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,Heikki Kovalainen,5,18,5,1,23,3,5,5,5,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [51]:
cols = []
for col in driver_race_df.columns: 
  cols.append(col) 
cols

['Driver',
 'resultId',
 'raceId',
 'driverId',
 'constructorId',
 'number_x',
 'grid',
 'position',
 'positionText',
 'positionOrder',
 'points',
 'laps',
 'time_x',
 'milliseconds',
 'fastestLap',
 'rank',
 'fastestLapTime',
 'fastestLapSpeed',
 'statusId',
 'driverRef',
 'number_y',
 'code',
 'forename',
 'surname',
 'dob',
 'nationality',
 'url_x',
 'year',
 'round',
 'circuitId',
 'name',
 'date',
 'time_y',
 'url_y',
 'fp1_date',
 'fp1_time',
 'fp2_date',
 'fp2_time',
 'fp3_date',
 'fp3_time',
 'quali_date',
 'quali_time',
 'sprint_date',
 'sprint_time']

In [57]:
rows_with_newline = driver_race_df[driver_race_df.apply(lambda x: x.str.contains('\n').any(), axis=1)]
print(rows_with_newline)

Empty DataFrame
Columns: [Driver, resultId, raceId, driverId, constructorId, number_x, grid, position, positionText, positionOrder, points, laps, time_x, milliseconds, fastestLap, rank, fastestLapTime, fastestLapSpeed, statusId, driverRef, number_y, code, forename, surname, dob, nationality, url_x, year, round, circuitId, name, date, time_y, url_y, fp1_date, fp1_time, fp2_date, fp2_time, fp3_date, fp3_time, quali_date, quali_time, sprint_date, sprint_time]
Index: []

[0 rows x 44 columns]

In [68]:
driver_race_df.replace(pd.NA, 0, regex=True) # Not working
driver_race_df.head()

,Driver,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,...,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,Lewis Hamilton,1,18,1,1,22,1,1,1,1,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,Nick Heidfeld,2,18,2,2,3,5,2,2,2,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,Nico Rosberg,3,18,3,3,7,7,3,3,3,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,Fernando Alonso,4,18,4,4,5,11,4,4,4,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,Heikki Kovalainen,5,18,5,1,23,3,5,5,5,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [78]:
#Calculate Average and total points

avg_points   = driver_race_df[['Driver','points']].groupby("Driver").mean()
total_points = driver_race_df[['Driver','points']].groupby("Driver").sum()

In [158]:
#Display Driver names greaterthan 50 race
n=driver_race_df[['Driver','raceId']].groupby("Driver").count()
num_races_df=n[n.raceId>50]
num_races_df = num_races_df.rename(columns={'raceId': 'Race_count'})
num_races_df

                    Race_count
Driver
Adrian Sutil               128
Aguri Suzuki                88
Alain Prost                202
Alan Jones                 117
Alessandro Nannini          77
...                        ...
Valtteri Bottas            201
Vitaly Petrov               58
Vitantonio Liuzzi           81
Vittorio Brambilla          78
Érik Comas                  63

[157 rows x 1 columns]