In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
from os import walk
import fastf1
import fastf1.plotting

In [2]:
folder = 'F1_Data'
fastf1.Cache.enable_cache('cache')

In [3]:
session = fastf1.get_session(2021, 22, 'R')

In [4]:
path = session.api_path

In [5]:
R_2019_Monza = fastf1.api.timing_data(path, response=None, livedata=None)

api            INFO 	Using cached data for timing_data

In [6]:
app = fastf1.api.timing_app_data(path, response=None, livedata=None)

api            INFO 	Using cached data for timing_app_data

In [7]:
app.sort_values(by='Time', inplace=True)

In [8]:
app[app['Driver']=='33'].head(50)

,LapNumber,Driver,LapTime,Stint,TotalLaps,Compound,New,TyresNotChanged,Time,LapFlags,LapCountTime,StartLaps,Outlap
10,NaN,33,NaT,0,3.0,SOFT,False,0,0 days 00:56:03.194000,0.0,None,3.0,None
21,NaN,33,NaT,0,4.0,None,None,None,0 days 01:03:58.244000,NaN,None,NaN,None
41,NaN,33,NaT,0,5.0,None,None,None,0 days 01:05:28.237000,NaN,None,NaN,None
44,2.0,33,0 days 00:01:29.103000,0,NaN,None,None,None,0 days 01:05:28.337000,1.0,None,NaN,None
77,3.0,33,0 days 00:01:28.827000,0,NaN,None,None,None,0 days 01:06:52.935000,NaN,None,NaN,None
78,NaN,33,NaT,0,6.0,None,None,None,0 days 01:06:53.256000,NaN,None,NaN,None
115,4.0,33,NaT,0,NaN,None,None,None,0 days 01:08:21.981000,NaN,None,NaN,None
116,NaN,33,NaT,0,7.0,None,None,None,0 days 01:08:23.249000,NaN,None,NaN,None
152,5.0,33,0 days 00:01:28.718000,0,NaN,None,None,None,0 days 01:09:50.682000,NaN,None,NaN,None
155,NaN,33,NaT,0,8.0,None,None,None,0 days 01:09:53.251000,NaN,None,NaN,None
187,6.0,33,0 days 00:01:28.707000,0,NaN,None,None,None,0 days 01:11:19.376000,NaN,None,NaN,None
189,NaN,33,NaT,0,9.0,None,None,None,0 days 01:11:23.257000,NaN,None,NaN,None
219,7.0,33,0 days 00:01:28.636000,0,NaN,None,None,None,0 days 01:12:47.991000,NaN,None,NaN,None
220,NaN,33,NaT,0,10.0,None,None,None,0 days 01:12:48.275000,NaN,None,NaN,None
254,8.0,33,NaT,0,NaN,None,None,None,0 days 01:14:16.815000,NaN,None,NaN,None
255,NaN,33,NaT,0,11.0,None,None,None,0 days 01:14:18.273000,NaN,None,NaN,None
289,NaN,33,NaT,0,12.0,None,None,None,0 days 01:15:48.282000,NaN,None,NaN,None
316,NaN,33,NaT,0,13.0,None,None,None,0 days 01:17:18.294000,NaN,None,NaN,None
343,NaN,33,NaT,0,14.0,None,None,None,0 days 01:18:48.284000,NaN,None,NaN,None
372,NaN,33,NaT,0,15.0,None,None,None,0 days 01:20:13.292000,NaN,None,NaN,None
404,NaN,33,NaT,0,16.0,None,None,None,0 days 01:21:48.298000,NaN,None,NaN,None
413,NaN,33,NaT,1,0.0,HARD,True,0,0 days 01:22:08.309000,0.0,None,0.0,None
435,NaN,33,NaT,1,1.0,None,None,None,0 days 01:23:33.320000,NaN,None,NaN,None
464,NaN,33,NaT,1,2.0,None,None,None,0 days 01:25:03.318000,NaN,None,NaN,None
466,NaN,33,NaT,0,NaN,None,None,None,0 days 01:25:03.337000,0.0,None,NaN,None
467,15.0,33,0 days 00:01:28.492000,1,NaN,None,None,None,0 days 01:25:03.337000,1.0,None,NaN,None
498,16.0,33,NaT,1,NaN,None,None,None,0 days 01:26:29.091000,NaN,None,NaN,None
499,NaN,33,NaT,1,3.0,None,None,None,0 days 01:26:33.343000,NaN,None,NaN,None
521,NaN,33,NaT,1,4.0,None,None,None,0 days 01:27:58.355000,NaN,None,NaN,None
552,NaN,33,NaT,1,5.0,None,None,None,0 days 01:29:28.373000,NaN,None,NaN,None
579,NaN,33,NaT,1,6.0,None,None,None,0 days 01:30:58.368000,NaN,None,NaN,None
607,20.0,33,0 days 00:01:28.387000,1,NaN,None,None,None,0 days 01:32:23.791000,NaN,None,NaN,None
608,NaN,33,NaT,1,7.0,None,None,None,0 days 01:32:28.384000,NaN,None,NaN,None
634,NaN,33,NaT,1,8.0,None,None,None,0 days 01:33:53.377000,NaN,None,NaN,None
661,22.0,33,0 days 00:01:28.322000,1,NaN,None,None,None,0 days 01:35:20.688000,NaN,None,NaN,None
662,NaN,33,NaT,1,9.0,None,None,None,0 days 01:35:23.397000,NaN,None,NaN,None
689,23.0,33,0 days 00:01:28.175000,1,NaN,None,None,None,0 days 01:36:48.822000,NaN,None,NaN,None
690,NaN,33,NaT,1,10.0,None,None,None,0 days 01:36:53.406000,NaN,None,NaN,None
725,24.0,33,NaT,1,NaN,None,None,None,0 days 01:38:17.004000,NaN,None,NaN,None
726,NaN,33,NaT,1,11.0,None,None,None,0 days 01:38:18.428000,NaN,None,NaN,None
751,25.0,33,0 days 00:01:28.041000,1,NaN,None,None,None,0 days 01:39:45.064000,NaN,None,NaN,None
752,NaN,33,NaT,1,12.0,None,None,None,0 days 01:39:48.427000,NaN,None,NaN,None
778,26.0,33,NaT,1,NaN,None,None,None,0 days 01:41:13.675000,NaN,None,NaN,None
779,NaN,33,NaT,1,13.0,None,None,None,0 days 01:41:18.441000,NaN,None,NaN,None
805,NaN,33,NaT,1,14.0,None,None,None,0 days 01:42:43.437000,NaN,None,NaN,None
828,28.0,33,0 days 00:01:27.935000,1,NaN,None,None,None,0 days 01:44:09.954000,NaN,None,NaN,None
829,NaN,33,NaT,1,15.0,None,None,None,0 days 01:44:13.459000,NaN,None,NaN,None
850,29.0,33,0 days 00:01:27.904000,1,NaN,None,None,None,0 days 01:45:37.837000,NaN,None,NaN,None
851,NaN,33,NaT,1,16.0,None,None,None,0 days 01:45:38.478000,NaN,None,NaN,None
878,30.0,33,0 days 00:01:27.678000,1,NaN,None,None,None,0 days 01:47:05.541000,NaN,None,NaN,None

In [9]:
weather = fastf1.api.weather_data(path, response=None, livedata=None)

api            INFO 	Using cached data for weather_data

In [10]:
weather['AirTemp']

[25.6,
 25.6,
 25.6,
 25.7,
 25.7,
 25.7,
 25.5,
 25.5,
 25.4,
 25.4,
 25.5,
 25.5,
 25.4,
 25.4,
 25.3,
 25.3,
 25.3,
 25.3,
 25.1,
 25.1,
 25.0,
 25.0,
 24.9,
 24.9,
 25.0,
 25.0,
 25.1,
 25.1,
 25.2,
 25.2,
 25.3,
 25.3,
 25.2,
 25.2,
 25.2,
 25.2,
 25.1,
 25.1,
 25.0,
 25.0,
 25.0,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.8,
 24.8,
 24.8,
 24.8,
 24.7,
 24.7,
 24.7,
 24.7,
 24.7,
 24.7,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.5,
 24.5,
 24.4,
 24.4,
 24.4,
 24.4,
 24.4,
 24.4,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.1,
 24.1,
 24.2,
 24.2,
 24.2,
 24.2,
 23.9,
 23.9,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.7,
 23.7,
 23.7,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.6,
 23.5,
 23.5,
 23.5,
 23.5]

In [11]:
weather['Time']

[datetime.timedelta(seconds=3, microseconds=778000),
 datetime.timedelta(seconds=63, microseconds=777000),
 datetime.timedelta(seconds=123, microseconds=779000),
 datetime.timedelta(seconds=183, microseconds=772000),
 datetime.timedelta(seconds=243, microseconds=783000),
 datetime.timedelta(seconds=303, microseconds=809000),
 datetime.timedelta(seconds=363, microseconds=807000),
 datetime.timedelta(seconds=423, microseconds=826000),
 datetime.timedelta(seconds=483, microseconds=823000),
 datetime.timedelta(seconds=543, microseconds=826000),
 datetime.timedelta(seconds=603, microseconds=840000),
 datetime.timedelta(seconds=663, microseconds=837000),
 datetime.timedelta(seconds=723, microseconds=857000),
 datetime.timedelta(seconds=783, microseconds=872000),
 datetime.timedelta(seconds=843, microseconds=869000),
 datetime.timedelta(seconds=903, microseconds=872000),
 datetime.timedelta(seconds=963, microseconds=869000),
 datetime.timedelta(seconds=1023, microseconds=869000),
 datetime.timedelta(seconds=1083, microseconds=868000),
 datetime.timedelta(seconds=1143, microseconds=884000),
 datetime.timedelta(seconds=1203, microseconds=885000),
 datetime.timedelta(seconds=1263, microseconds=901000),
 datetime.timedelta(seconds=1323, microseconds=918000),
 datetime.timedelta(seconds=1383, microseconds=925000),
 datetime.timedelta(seconds=1443, microseconds=915000),
 datetime.timedelta(seconds=1503, microseconds=931000),
 datetime.timedelta(seconds=1563, microseconds=948000),
 datetime.timedelta(seconds=1623, microseconds=946000),
 datetime.timedelta(seconds=1683, microseconds=948000),
 datetime.timedelta(seconds=1743, microseconds=952000),
 datetime.timedelta(seconds=1803, microseconds=948000),
 datetime.timedelta(seconds=1863, microseconds=947000),
 datetime.timedelta(seconds=1923, microseconds=963000),
 datetime.timedelta(seconds=1983, microseconds=961000),
 datetime.timedelta(seconds=2043, microseconds=991000),
 datetime.timedelta(seconds=2103, microseconds=993000),
 datetime.timedelta(seconds=2163, microseconds=998000),
 datetime.timedelta(seconds=2223, microseconds=993000),
 datetime.timedelta(seconds=2283, microseconds=994000),
 datetime.timedelta(seconds=2343, microseconds=997000),
 datetime.timedelta(seconds=2403, microseconds=996000),
 datetime.timedelta(seconds=2463, microseconds=999000),
 datetime.timedelta(seconds=2523, microseconds=995000),
 datetime.timedelta(seconds=2583, microseconds=994000),
 datetime.timedelta(seconds=2643, microseconds=994000),
 datetime.timedelta(seconds=2704, microseconds=12000),
 datetime.timedelta(seconds=2764, microseconds=27000),
 datetime.timedelta(seconds=2824, microseconds=25000),
 datetime.timedelta(seconds=2884, microseconds=29000),
 datetime.timedelta(seconds=2944, microseconds=31000),
 datetime.timedelta(seconds=3004, microseconds=28000),
 datetime.timedelta(seconds=3064, microseconds=25000),
 datetime.timedelta(seconds=3124, microseconds=25000),
 datetime.timedelta(seconds=3184, microseconds=39000),
 datetime.timedelta(seconds=3244, microseconds=26000),
 datetime.timedelta(seconds=3304, microseconds=27000),
 datetime.timedelta(seconds=3364, microseconds=27000),
 datetime.timedelta(seconds=3424, microseconds=26000),
 datetime.timedelta(seconds=3484, microseconds=27000),
 datetime.timedelta(seconds=3544, microseconds=26000),
 datetime.timedelta(seconds=3604, microseconds=28000),
 datetime.timedelta(seconds=3664, microseconds=28000),
 datetime.timedelta(seconds=3724, microseconds=25000),
 datetime.timedelta(seconds=3784, microseconds=27000),
 datetime.timedelta(seconds=3844, microseconds=26000),
 datetime.timedelta(seconds=3904, microseconds=42000),
 datetime.timedelta(seconds=3964, microseconds=30000),
 datetime.timedelta(seconds=4024, microseconds=44000),
 datetime.timedelta(seconds=4084, microseconds=42000),
 datetime.timedelta(seconds=4144, microseconds=41000),
 datetime.timedelta(seconds=4204, microseconds=48000),
 datetime.timedelta(seconds=4264, microseconds=42000),
 datetime.timedelta(seconds=4324, microseconds=66000),
 datetime.timedelta(seconds=4384, microseconds=73000),
 datetime.timedelta(seconds=4444, microseconds=95000),
 datetime.timedelta(seconds=4504, microseconds=105000),
 datetime.timedelta(seconds=4564, microseconds=104000),
 datetime.timedelta(seconds=4624, microseconds=119000),
 datetime.timedelta(seconds=4684, microseconds=138000),
 datetime.timedelta(seconds=4744, microseconds=138000),
 datetime.timedelta(seconds=4804, microseconds=135000),
 datetime.timedelta(seconds=4864, microseconds=153000),
 datetime.timedelta(seconds=4924, microseconds=151000),
 datetime.timedelta(seconds=4984, microseconds=160000),
 datetime.timedelta(seconds=5044, microseconds=152000),
 datetime.timedelta(seconds=5104, microseconds=174000),
 datetime.timedelta(seconds=5164, microseconds=181000),
 datetime.timedelta(seconds=5224, microseconds=199000),
 datetime.timedelta(seconds=5284, microseconds=198000),
 datetime.timedelta(seconds=5344, microseconds=204000),
 datetime.timedelta(seconds=5404, microseconds=198000),
 datetime.timedelta(seconds=5464, microseconds=202000),
 datetime.timedelta(seconds=5524, microseconds=224000),
 datetime.timedelta(seconds=5584, microseconds=237000),
 datetime.timedelta(seconds=5644, microseconds=244000),
 datetime.timedelta(seconds=5704, microseconds=271000),
 datetime.timedelta(seconds=5764, microseconds=245000),
 datetime.timedelta(seconds=5824, microseconds=259000),
 datetime.timedelta(seconds=5884, microseconds=264000),
 datetime.timedelta(seconds=5944, microseconds=260000),
 datetime.timedelta(seconds=6004, microseconds=264000),
 datetime.timedelta(seconds=6064, microseconds=267000),
 datetime.timedelta(seconds=6124, microseconds=292000),
 datetime.timedelta(seconds=6184, microseconds=276000),
 datetime.timedelta(seconds=6244, microseconds=274000),
 datetime.timedelta(seconds=6304, microseconds=472000),
 datetime.timedelta(seconds=6364, microseconds=275000),
 datetime.timedelta(seconds=6424, microseconds=279000),
 datetime.timedelta(seconds=6484, microseconds=282000),
 datetime.timedelta(seconds=6544, microseconds=276000),
 datetime.timedelta(seconds=6604, microseconds=276000),
 datetime.timedelta(seconds=6664, microseconds=275000),
 datetime.timedelta(seconds=6724, microseconds=281000),
 datetime.timedelta(seconds=6784, microseconds=275000),
 datetime.timedelta(seconds=6844, microseconds=277000),
 datetime.timedelta(seconds=6904, microseconds=276000),
 datetime.timedelta(seconds=6964, microseconds=278000),
 datetime.timedelta(seconds=7024, microseconds=279000),
 datetime.timedelta(seconds=7084, microseconds=277000),
 datetime.timedelta(seconds=7144, microseconds=280000),
 datetime.timedelta(seconds=7204, microseconds=278000),
 datetime.timedelta(seconds=7264, microseconds=276000),
 datetime.timedelta(seconds=7324, microseconds=285000),
 datetime.timedelta(seconds=7384, microseconds=277000),
 datetime.timedelta(seconds=7444, microseconds=279000),
 datetime.timedelta(seconds=7504, microseconds=285000),
 datetime.timedelta(seconds=7564, microseconds=276000),
 datetime.timedelta(seconds=7624, microseconds=278000),
 datetime.timedelta(seconds=7684, microseconds=277000),
 datetime.timedelta(seconds=7744, microseconds=273000),
 datetime.timedelta(seconds=7804, microseconds=281000),
 datetime.timedelta(seconds=7864, microseconds=280000),
 datetime.timedelta(seconds=7924, microseconds=276000),
 datetime.timedelta(seconds=7984, microseconds=284000),
 datetime.timedelta(seconds=8044, microseconds=279000),
 datetime.timedelta(seconds=8104, microseconds=303000),
 datetime.timedelta(seconds=8164, microseconds=276000),
 datetime.timedelta(seconds=8224, microseconds=276000),
 datetime.timedelta(seconds=8284, microseconds=277000),
 datetime.timedelta(seconds=8344, microseconds=283000),
 datetime.timedelta(seconds=8404, microseconds=275000),
 datetime.timedelta(seconds=8464, microseconds=279000),
 datetime.timedelta(seconds=8524, microseconds=277000),
 datetime.timedelta(seconds=8584, microseconds=275000),
 datetime.timedelta(seconds=8644, microseconds=282000),
 datetime.timedelta(seconds=8704, microseconds=305000),
 datetime.timedelta(seconds=8764, microseconds=334000),
 datetime.timedelta(seconds=8824, microseconds=326000),
 datetime.timedelta(seconds=8884, microseconds=324000),
 datetime.timedelta(seconds=8944, microseconds=332000),
 datetime.timedelta(seconds=9004, microseconds=324000),
 datetime.timedelta(seconds=9064, microseconds=322000),
 datetime.timedelta(seconds=9124, microseconds=327000),
 datetime.timedelta(seconds=9184, microseconds=331000),
 datetime.timedelta(seconds=9244, microseconds=324000),
 datetime.timedelta(seconds=9304, microseconds=323000),
 datetime.timedelta(seconds=9364, microseconds=326000)]

In [12]:
weather['AirTemp']

[25.6,
 25.6,
 25.6,
 25.7,
 25.7,
 25.7,
 25.5,
 25.5,
 25.4,
 25.4,
 25.5,
 25.5,
 25.4,
 25.4,
 25.3,
 25.3,
 25.3,
 25.3,
 25.1,
 25.1,
 25.0,
 25.0,
 24.9,
 24.9,
 25.0,
 25.0,
 25.1,
 25.1,
 25.2,
 25.2,
 25.3,
 25.3,
 25.2,
 25.2,
 25.2,
 25.2,
 25.1,
 25.1,
 25.0,
 25.0,
 25.0,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.9,
 24.8,
 24.8,
 24.8,
 24.8,
 24.7,
 24.7,
 24.7,
 24.7,
 24.7,
 24.7,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.5,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.6,
 24.5,
 24.5,
 24.4,
 24.4,
 24.4,
 24.4,
 24.4,
 24.4,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.3,
 24.1,
 24.1,
 24.2,
 24.2,
 24.2,
 24.2,
 23.9,
 23.9,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.7,
 23.7,
 23.7,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.8,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.7,
 23.6,
 23.5,
 23.5,
 23.5,
 23.5]

In [13]:
weather['Humidity']

[53.5,
 52.6,
 53.3,
 53.3,
 53.3,
 52.8,
 52.1,
 52.3,
 52.5,
 52.4,
 52.1,
 52.3,
 53.0,
 53.8,
 55.0,
 55.0,
 55.7,
 56.0,
 56.4,
 56.0,
 56.6,
 56.5,
 55.6,
 56.0,
 56.3,
 56.4,
 56.5,
 56.5,
 55.7,
 55.6,
 56.0,
 55.6,
 56.0,
 56.3,
 55.9,
 55.7,
 55.5,
 55.2,
 55.2,
 55.1,
 54.6,
 54.3,
 55.1,
 54.6,
 54.6,
 53.8,
 53.8,
 54.1,
 54.2,
 54.2,
 54.4,
 55.2,
 55.9,
 56.1,
 56.1,
 56.9,
 56.9,
 57.3,
 57.3,
 57.7,
 57.8,
 57.6,
 57.6,
 58.0,
 58.0,
 57.6,
 57.6,
 57.5,
 57.5,
 58.3,
 58.3,
 58.1,
 58.1,
 58.0,
 58.0,
 58.3,
 58.3,
 57.3,
 57.3,
 57.6,
 57.6,
 58.2,
 59.0,
 59.0,
 59.0,
 59.4,
 59.4,
 59.3,
 59.8,
 59.6,
 59.8,
 60.0,
 59.8,
 59.9,
 59.9,
 59.6,
 59.8,
 60.2,
 60.1,
 60.4,
 60.6,
 60.9,
 61.3,
 61.0,
 61.1,
 61.5,
 61.5,
 61.4,
 61.6,
 61.7,
 61.7,
 61.9,
 61.9,
 62.1,
 62.4,
 62.5,
 62.7,
 63.0,
 63.0,
 63.6,
 63.6,
 64.2,
 64.2,
 64.3,
 64.3,
 64.4,
 64.4,
 64.6,
 64.6,
 64.6,
 64.6,
 64.6,
 64.6,
 64.8,
 64.8,
 64.8,
 64.9,
 64.7,
 64.7,
 64.5,
 64.7,
 64.3,
 64.3,
 64.6,
 64.6,
 64.5,
 64.5,
 64.1,
 64.1,
 64.6,
 64.6,
 64.9,
 64.9,
 65.2,
 65.2,
 64.8,
 64.8]

In [14]:
RC = fastf1.api.race_control_messages(path, response=None, livedata=None)

api            INFO 	Using cached data for race_control_messages

In [15]:
RC.keys()

dict_keys(['Time', 'Category', 'Message', 'Status', 'Flag', 'Scope', 'Sector', 'RacingNumber'])

In [16]:
RC['Time']

[datetime.datetime(2021, 12, 12, 12, 20, 1),
 datetime.datetime(2021, 12, 12, 12, 30, 1),
 datetime.datetime(2021, 12, 12, 12, 47, 17),
 datetime.datetime(2021, 12, 12, 12, 57, 6),
 datetime.datetime(2021, 12, 12, 13, 3, 22),
 datetime.datetime(2021, 12, 12, 13, 4, 33),
 datetime.datetime(2021, 12, 12, 13, 6, 19),
 datetime.datetime(2021, 12, 12, 13, 6, 35),
 datetime.datetime(2021, 12, 12, 13, 8, 19),
 datetime.datetime(2021, 12, 12, 13, 9, 53),
 datetime.datetime(2021, 12, 12, 13, 23, 39),
 datetime.datetime(2021, 12, 12, 13, 27, 47),
 datetime.datetime(2021, 12, 12, 13, 30, 3),
 datetime.datetime(2021, 12, 12, 13, 31, 30),
 datetime.datetime(2021, 12, 12, 13, 41, 6),
 datetime.datetime(2021, 12, 12, 13, 41, 7),
 datetime.datetime(2021, 12, 12, 13, 41, 30),
 datetime.datetime(2021, 12, 12, 13, 41, 41),
 datetime.datetime(2021, 12, 12, 13, 41, 47),
 datetime.datetime(2021, 12, 12, 13, 41, 47),
 datetime.datetime(2021, 12, 12, 13, 41, 47),
 datetime.datetime(2021, 12, 12, 13, 42, 13),
 datetime.datetime(2021, 12, 12, 13, 44, 11),
 datetime.datetime(2021, 12, 12, 13, 44, 19),
 datetime.datetime(2021, 12, 12, 13, 44, 27),
 datetime.datetime(2021, 12, 12, 13, 48, 35),
 datetime.datetime(2021, 12, 12, 13, 49, 34),
 datetime.datetime(2021, 12, 12, 13, 50, 10),
 datetime.datetime(2021, 12, 12, 13, 50, 48),
 datetime.datetime(2021, 12, 12, 13, 55),
 datetime.datetime(2021, 12, 12, 13, 56, 3),
 datetime.datetime(2021, 12, 12, 13, 56, 5),
 datetime.datetime(2021, 12, 12, 13, 58, 53),
 datetime.datetime(2021, 12, 12, 13, 59),
 datetime.datetime(2021, 12, 12, 13, 59, 6),
 datetime.datetime(2021, 12, 12, 13, 59, 9),
 datetime.datetime(2021, 12, 12, 13, 59, 13),
 datetime.datetime(2021, 12, 12, 14, 0, 41),
 datetime.datetime(2021, 12, 12, 14, 1, 11),
 datetime.datetime(2021, 12, 12, 14, 1, 58),
 datetime.datetime(2021, 12, 12, 14, 2, 46),
 datetime.datetime(2021, 12, 12, 14, 6, 38),
 datetime.datetime(2021, 12, 12, 14, 7, 54),
 datetime.datetime(2021, 12, 12, 14, 9, 41),
 datetime.datetime(2021, 12, 12, 14, 11, 4),
 datetime.datetime(2021, 12, 12, 14, 11, 20),
 datetime.datetime(2021, 12, 12, 14, 11, 51),
 datetime.datetime(2021, 12, 12, 14, 11, 52),
 datetime.datetime(2021, 12, 12, 14, 12, 28),
 datetime.datetime(2021, 12, 12, 14, 12, 36),
 datetime.datetime(2021, 12, 12, 14, 13, 3),
 datetime.datetime(2021, 12, 12, 14, 13, 50),
 datetime.datetime(2021, 12, 12, 14, 14, 15),
 datetime.datetime(2021, 12, 12, 14, 19, 22),
 datetime.datetime(2021, 12, 12, 14, 20, 43),
 datetime.datetime(2021, 12, 12, 14, 20, 58),
 datetime.datetime(2021, 12, 12, 14, 21, 38),
 datetime.datetime(2021, 12, 12, 14, 21, 51),
 datetime.datetime(2021, 12, 12, 14, 21, 51),
 datetime.datetime(2021, 12, 12, 14, 21, 54),
 datetime.datetime(2021, 12, 12, 14, 23, 16),
 datetime.datetime(2021, 12, 12, 14, 27, 55),
 datetime.datetime(2021, 12, 12, 14, 31, 1),
 datetime.datetime(2021, 12, 12, 14, 31, 19),
 datetime.datetime(2021, 12, 12, 14, 31, 28),
 datetime.datetime(2021, 12, 12, 14, 31, 31),
 datetime.datetime(2021, 12, 12, 14, 32, 2),
 datetime.datetime(2021, 12, 12, 14, 32, 2),
 datetime.datetime(2021, 12, 12, 14, 32, 12),
 datetime.datetime(2021, 12, 12, 14, 32, 13),
 datetime.datetime(2021, 12, 12, 14, 32, 15),
 datetime.datetime(2021, 12, 12, 14, 32, 17),
 datetime.datetime(2021, 12, 12, 14, 32, 42),
 datetime.datetime(2021, 12, 12, 14, 33, 38)]

In [17]:
TS = fastf1.api.track_status_data(path, response=None, livedata=None)

api            INFO 	Using cached data for track_status_data

In [18]:
TS.keys()

dict_keys(['Time', 'Status', 'Message'])

In [19]:
TS['Time']

[datetime.timedelta(0),
 datetime.timedelta(seconds=6006, microseconds=247000),
 datetime.timedelta(seconds=6047, microseconds=317000),
 datetime.timedelta(seconds=6903, microseconds=19000),
 datetime.timedelta(seconds=7073, microseconds=608000),
 datetime.timedelta(seconds=7086, microseconds=176000),
 datetime.timedelta(seconds=8438, microseconds=379000),
 datetime.timedelta(seconds=8454, microseconds=313000),
 datetime.timedelta(seconds=9062, microseconds=298000)]

In [29]:
# add the LapStartTime from API to the app dataframe 
app['LapStartTime'] = app['Time'] - app['LapTime']

app.head()

,Driver,LapStartTime,LapTime,Time,LapNumber,Stint,Compound,New,TyresNotChanged,LapFlags,LapCountTime,StartLaps,Outlap
1550,5,0 days 02:32:18.785000,0 days 00:01:28.303000,0 days 02:33:47.088000,58.0,1,None,None,None,NaN,None,NaN,None
1547,31,0 days 02:32:15.329000,0 days 00:01:28.249000,0 days 02:33:43.578000,58.0,1,None,None,None,NaN,None,NaN,None
1546,14,0 days 02:32:13.666000,0 days 00:01:27.607000,0 days 02:33:41.273000,58.0,1,None,None,None,NaN,None,NaN,None
1545,4,0 days 02:32:11.983000,0 days 00:01:26.762000,0 days 02:33:38.745000,58.0,2,None,None,None,NaN,None,NaN,None
1536,10,0 days 02:31:17.752000,0 days 00:01:28.344000,0 days 02:32:46.096000,58.0,2,None,None,None,NaN,None,NaN,None

In [30]:
# Reorder columns as driver, LapStartTime, LapTime, Time, LapNumber, Stint, Compound, New, TyresNotChanged, LapFlags, LapCountTime, StartLaps, Outlap
app = app[['Driver', 'LapStartTime', 'LapTime', 'Time', 'LapNumber', 'Stint', 'Compound', 'New', 'TyresNotChanged', 'LapFlags', 'LapCountTime', 'StartLaps', 'Outlap']]


app.head(100)

,Driver,LapStartTime,LapTime,Time,LapNumber,Stint,Compound,New,TyresNotChanged,LapFlags,LapCountTime,StartLaps,Outlap
1550,5,0 days 02:32:18.785000,0 days 00:01:28.303000,0 days 02:33:47.088000,58.0,1,None,None,None,NaN,None,NaN,None
1547,31,0 days 02:32:15.329000,0 days 00:01:28.249000,0 days 02:33:43.578000,58.0,1,None,None,None,NaN,None,NaN,None
1546,14,0 days 02:32:13.666000,0 days 00:01:27.607000,0 days 02:33:41.273000,58.0,1,None,None,None,NaN,None,NaN,None
1545,4,0 days 02:32:11.983000,0 days 00:01:26.762000,0 days 02:33:38.745000,58.0,2,None,None,None,NaN,None,NaN,None
1536,10,0 days 02:31:17.752000,0 days 00:01:28.344000,0 days 02:32:46.096000,58.0,2,None,None,None,NaN,None,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,3,0 days 01:52:29.053000,0 days 00:01:28.817000,0 days 01:53:57.870000,34.0,1,None,None,None,NaN,None,NaN,None
997,77,0 days 01:52:19.910000,0 days 00:01:27.918000,0 days 01:53:47.828000,34.0,1,None,None,None,NaN,None,NaN,None
996,4,0 days 01:52:16.362000,0 days 00:01:28.801000,0 days 01:53:45.163000,34.0,1,None,None,None,NaN,None,NaN,None
992,55,0 days 01:52:14.403000,0 days 00:01:28.828000,0 days 01:53:43.231000,34.0,1,None,None,None,NaN,None,NaN,None
991,10,0 days 01:52:12.144000,0 days 00:01:28.998000,0 days 01:53:41.142000,34.0,0,None,None,None,NaN,None,NaN,None

In [31]:
app["LapStartTime"].nunique()

319

In [32]:
# sort app data frame by lap start time, time, and lap time in descending order
app.sort_values(by=['LapStartTime', 'Time', 'LapTime'], ascending=False, inplace=True)
app.head()

,Driver,LapStartTime,LapTime,Time,LapNumber,Stint,Compound,New,TyresNotChanged,LapFlags,LapCountTime,StartLaps,Outlap
1550,5,0 days 02:32:18.785000,0 days 00:01:28.303000,0 days 02:33:47.088000,58.0,1,None,None,None,NaN,None,NaN,None
1547,31,0 days 02:32:15.329000,0 days 00:01:28.249000,0 days 02:33:43.578000,58.0,1,None,None,None,NaN,None,NaN,None
1546,14,0 days 02:32:13.666000,0 days 00:01:27.607000,0 days 02:33:41.273000,58.0,1,None,None,None,NaN,None,NaN,None
1545,4,0 days 02:32:11.983000,0 days 00:01:26.762000,0 days 02:33:38.745000,58.0,2,None,None,None,NaN,None,NaN,None
1536,10,0 days 02:31:17.752000,0 days 00:01:28.344000,0 days 02:32:46.096000,58.0,2,None,None,None,NaN,None,NaN,None